feat:#43 議会の項目を追加した
mct-joken/mct-student-association pull request #54
Opened 2023-06-11 22:44 UTC by kiji-haru

Close #43
こんな感じでいいですか
![Screenshot 2023-06-12 at 7 42 32](https://github.com/mct-joken/mct-student-association/assets/74781355/fd692472-5ff8-4c84-92cb-37491dd654f2)

2023-06-11 22:44 UTC, kiji-haru commented
あと松江高専の議会の仕事ってなんだ?(純粋な疑問)

2023-06-11 22:59 UTC, kiji-haru commented
JSOCなの見落としてた(バカ)
すまん消してもええ

2023-06-14 11:24 UTC, laminne requested changes
１箇所気になるところがありました

2023-06-14 11:24 UTC, laminne commented on src/pages/members.tsx
> +  <div id="gikai">
ここ、L16(19)の配列に入れずに新しく生やしてる理由ってありますか？

2023-06-14 11:28 UTC, kiji-haru commented on src/pages/members.tsx
> +  <div id="gikai">
前に、今の状態が良いから議会の分はこれとは別に生やそうと言う話をした記憶があるので

2023-06-15 00:40 UTC, laminne commented on src/pages/members.tsx
> +  <div id="gikai">
ん〜、配列の中に入れろとは言わないけど、そこから生成されたのと同じdiv要素に入れるべきとは思う

2023-06-23 08:26 UTC, laminne approved these changes

2023-06-23 08:48 UTC, laminne approved these changes

2023-06-23 08:49 UTC, merged