fix: メニューを開いた状態でホームに戻ろうとするとメニューが閉じない不具合の修正
mct-joken/mct-student-association pull request #63
Opened 2023-06-15 02:40 UTC by Suzune2741

Close #60 
メニュー開いたら戻らなかったのでHeaderもfooterと同じ感じにしました

2023-06-15 02:53 UTC, tufusa requested changes

2023-06-15 02:53 UTC, tufusa commented on src/components/ResponsiveHeader/narrowHeader.tsx
> +  <div className={styles.li}>
`className={styles.li}`　これ何ですか？

2023-06-15 03:59 UTC, tufusa commented on src/components/ResponsiveHeader/narrowHeader.tsx
> +  <div className={styles.li}>
`narrowHeader.module.css`に`.li`は無いのでtypoですかね？

2023-06-16 05:50 UTC, Suzune2741 commented on src/components/ResponsiveHeader/narrowHeader.tsx
> +  <div className={styles.li}>
持ってきた後に変更を忘れていました
className={styles['primary-header-link']}に変更しました

2023-06-18 00:40 UTC, tufusa commented on src/components/ResponsiveHeader/narrowHeader.tsx
> +  <div className={styles['primary-header-link']}>
`Link`自体に`className={styles['primary-header-link']}`がついているので、L27の`div`は不要っぽいです
なのでこの`LinkItem`自体いらない気がします

2023-06-18 00:40 UTC, tufusa commented on src/components/ResponsiveHeader/narrowHeader.tsx
> +        <LinkItem to="/" children="松江高専　学生会"  setNavOpen={props.setNavOpen} />
```suggestion
        <Link
          to="/"
          children="松江高専　学生会"
          onClick={() => props.setNavOpen(false)}
          className={styles['primary-header-link']}
        />
```

2023-06-18 00:40 UTC, tufusa commented on src/components/ResponsiveHeader/narrowHeader.tsx
> +  <div className={styles['primary-header-link']}>
`LinkItem`は`List Item`(`li`タグのこと)になぞらえた名前で、同じスタイルの`Link`を複数個並べる時に共通部分を省略するためのものです(わかりづらくてごめん)

2023-06-23 03:44 UTC, tufusa approved these changes

2023-06-23 03:50 UTC, merged