fix:map()メソッド内の要素でkeyプロパティが欠けている箇所を修正
mct-joken/mct-student-association pull request #66
Opened 2023-06-15 14:02 UTC by kiji-haru

2023-06-15 14:06 UTC, laminne requested changes
気になる部分がありました、確認をお願いします

2023-06-15 14:06 UTC, laminne commented on src/pages/clubs.tsx
> +      {athletic_clubs.map((club, index) => (
完全に静的な情報だから良いかもしれないけど、KeyにIndexを入れるのはアンチパターンらしい
indexじゃなく、club.name(あるか知らないけど)あたりを使うべきだと思う
cf. https://zenn.dev/luvmini511/articles/f7b22d93e9c182

2023-06-15 15:13 UTC, kiji-haru commented
そのようにしました

2023-06-21 05:58 UTC, laminne approved these changes
LGTM

2023-06-21 06:42 UTC, merged